sudo: false
language: node_js

node_js:
 - 'node'
 - 8

script:
 - npm run lint
 - npm run test
 - npm run build

jobs:
 include:
   - stage: Deploy
     script:
       - npm run build
     deploy:
       provider: heroku
       app: shri-hometask-5-v1
       skip_cleanup: true