sudo: false
language: node_js

node_js:
 - 'node'
 - 8

script:
 - npm run lint
 - npm run test
 - npm run build

jobs:
 include:
   - stage: Deploy
     script:
       - npm run build
     deploy:
       provider: heroku
       app: shri-hometask-5-v1
       api_key:
         secure: wanGW2fiqT1im662j5VB9YrVDNvHpOulqEIeIyaNddXG1lUgt5G8SwmkNHoxwUYua82vRIYjRKqCZZva+tMiZK77Q0fKC5JhD8HKUyBWz4jAnXpDdZk862HLey3LrnyieZBhPsjRBtK7JOQ6DtUA7mFebH6B37nr++AnIHzpNCHK+90E/i5s3DLqWC8yZMnQEB1bHfydU/1Q6gv3jDoetMlZGsWbXPLi6w4ISoslTDbsMpaHY9iVyDnjawglNxz0qD0dZDG4wJwWuLQP9bIMydi+1ap/TPPRfncTQ//Onhgn9hPpifUG9lkMm+Z88mbWhjrA40VHtkPu1XFCZoPhrnIp8hen1HTo9qjZcp2JLOxrxcufq03ZbCz/oew667WVQOCc7mchBVUgaUYOZHCYVEssp0ELl4NhBOih5ICHOrSvsrhwxFDWTyMxyWdcZrBrDy9U66pSegSEUrT6UVfZaBBeoUiuV+D9jlDZ04LVQBKiEMdG9wQDQnEZgc6czST6sySGTCtSR0aBZG/fmy4zwgCGyoVQ+NstUtAb8qmvnT/4xm2fe0A7fK5jPqTAq9wkPL+uf78uN4s5w8pREF+uCJ9Hd1PxdPBeMSOaU83Ff/Fib1CrYvse6gN3pV0CGMBXuswHq/g3SW0bre0zlT6tBZ9r12d1n0kvize9Q++CdnU=
       skip_cleanup: true